---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: "talos.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["29d25e78-c721-45fe-a214-1399da755d98.cfargotunnel.com"]
