# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:FS20Gx8Q/UwEACX1O+HnEuvzeWCGLqpIGIu36Rv8Z+5/EQ01d/cOGw==,iv:MO4Cbt3Eq4TiM+9u25Z5GnSIh1av9g4+CeOVDEN7ynI=,tag:/bjFLv/5fozOaP/KTjhTRw==,type:str]
sops:
  age:
    - recipient: age14c693pdqe6ucz358tteussmwt96fyqz2zs8d656td2av3y0s7ugqklja8z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ1drYUZ4UHJiSmQ3Ulox
        MVRjbEpaOUJXUElWRFE4aEJGenFCdXdIeVdzCkJhZndZZm04TlRNVHlRcnFBcU5p
        ZERjTnNQeXYrOWg1ODlzV2xrRXNwYjgKLS0tIEpQRzV5RGpVaHIvaTFIeUtsM3dB
        SnNieHJaMGhRUnRNZ0RtYm1jQStMT3cKRZsnn8+zopKqXRZZJw/kRT3lfAm2092n
        rWTv9o+mhiXaPfgQlPD/PHOjM1QdF1gtLttZRFrSCK1dopSBflGueA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-29T13:14:03Z"
  mac: ENC[AES256_GCM,data:5qFovZVSSJBDQuNUlrNXBJEqK06qwYd3l49Dl7KWZf0FgykVnkSZWbnQlexr0fjaW/aOudNNqi6CPNoJdQvq7Gt4eM0kWpozvbLaRnxAcNpUVBsXFMx11mOwKjQOVS3aSAe2rLOysHh2Q+ps+KuApHC7x7DoebnUZC9FlqAsKkA=,iv:kX3xFUavxPs5VmLI+hD6btThN21+berLwQjSXU+59js=,tag:8xIUctHB4QoO86msFxbBig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
