apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jCDSA5qaF4nAOW+2,iv:qXRiFoVmHWMrD4s+n0hrDF5hkT2mJp8ur16VeVor8lg=,tag:s0QlwrJ+MNIJmjBGG8ysJQ==,type:str]
sops:
  age:
    - recipient: age14c693pdqe6ucz358tteussmwt96fyqz2zs8d656td2av3y0s7ugqklja8z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbGQvcGRxRTVMUG01dTB2
        RFVKSkY4UW1tZVRNNUx2a1JpS0g3UEhuaENRCnAyMVdQSWJIUUNOSXY1N25sMTFK
        bC9JQVBRYnFXRElPOUlEVmlqVU5ZWGMKLS0tIEpzZ3crN2FRQkNQalErTTJWUURo
        YUxicUQ1QUR5VWlsOGpXZ0pkNFR1U28K2rThJoQ5boYmJWmxz6pFaZ6RKkYO7hTd
        q/vSSNSyvnXx9EqK7uOAGJw5mZRdLYtJnqYk5D316pFlRN2Yb71cCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-20T16:45:36Z"
  mac: ENC[AES256_GCM,data:dEFSzSNamnY4595lDQrQAN3ReL55LwfnLrV0NMU8qqOzUf2wJv/4AMt/1dbRi9ObixGx6sc1xIIEiIyxjJVDEpqEsNm2cSOI1kAWL/wBNv8Y9RxkYeHO/Pu1DrhpyODCNH//vmJm5TpY6caA5vfQ5FeVu0tWcpkpprPKEeqMUxc=,iv:OBgsussxzrtjsX67orrmCbLH/RHiLer+Jgt0E9XZXs0=,tag:oZd/fjVI9kE0W+f5MDtGZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
