# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Oa8DXjX1JOBnDpsHvVFdY/OUxBSrb4pPCK8lA+wzf3Rxa6YxK1xaFA==,iv:2napnIMdz/i5j19dfhveHvUWUgs+BlI9ZzNkWAeZwd8=,tag:vALjR2K6oTrF1JQXWkxgAQ==,type:str]
sops:
  age:
    - recipient: age14c693pdqe6ucz358tteussmwt96fyqz2zs8d656td2av3y0s7ugqklja8z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdGRuc1VBajJPSjRCTTNX
        SUUxeVNYc0VRZWRBTGthS0xjbzNEdFlzZ1ZRCmJZcSsreWF4a0pBMHBSckJYOS85
        V0dxdTVORnp6RkZ5SVhvK3FJY2d2aVkKLS0tIHo4cE8rTG5ydmpXb0lWUnptOGtn
        MEREejhJNXNBZDBlak9USlhiNVlhL2sK2NSv62UxmBjEFXdy/f1ETBnbgv6l6OcH
        a0J3xkwdXpHULlwlMwizLip0PIajEIINLv+iEQoswKMDFb6cO8HShw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-07T16:25:58Z"
  mac: ENC[AES256_GCM,data:ZAnDbk89W+6vpmPoY8mK31Crh+FM35qJcz6YEy7/64Gbv/9Tzg1fjj/sHg17wZzOJ7iaS4elk8BVmVZ2+QcQg06JgbZgdu7ygIGfCDbyDSbtLX0tARrSsxxLoVAUxkRWhuqOzOIcEUQR2qs9vG+8zoL6c3ehclcFun7mSlu/o9w=,iv:sXd5Z9X6H9HzBe5q3+5A+Zb1p0PY5AfUMJIw8xzUYaU=,tag:k1JF77BCj28UQlc0Zyj61w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
