---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bind-dns
spec:
  chartRef:
    kind: OCIRepository
    name: bind-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider:
      name: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: &secret bind-dns-secret
            key: rfc2136_tsig_secret
    extraArgs:
      - --rfc2136-host=${PRIVATE_DNS_PRIMARY}
      - --rfc2136-port=53
      - --rfc2136-zone=${SECRET_DOMAIN}
      - --rfc2136-zone=${MAIN_DOMAIN}
      - --rfc2136-min-ttl=0s
      - --rfc2136-tsig-axfr
      - --rfc2136-tsig-keyname=externaldns
      - --rfc2136-tsig-secret-alg=hmac-sha256
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - gateway-httproute
      - service
    # we cannot create TXT records on hosts with with CNAME records with BIND, so use txtPrefix also.
    txtOwnerId: uvt
    txtPrefix: uvt+
    domainFilters:
      - ${SECRET_DOMAIN}
      - ${MAIN_DOMAIN}
    logLevel: info
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        memory: 192Mi
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
