---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
      backupTarget: s3://longhorn@ca-east-1/
      backupTargetCredentialSecret: longhorn-secret
      defaultReplicaCount: 3
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/mnt/extra/longhorn
      restoreVolumeRecurringJobs: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 1
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      taintToleration: CriticalAddonsOnly:Exists; node-role.kubernetes.io/control-plane:NoSchedule
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
    longhornDriver:
      tolerations: &tolerations
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
    longhornManager:
      tolerations: *tolerations
