apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  PRIVATE_DNS_PRIMARY: ENC[AES256_GCM,data:EsjiS7SkSmdwIzo=,iv:tBBB4iOIgX/9AQcKRmOjbKIWo6icm82+n4N74E5UMRE=,tag:A5pHiQmYQH2uSeNryJ1vOA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:+Hz3gmXFN66s,iv:j1+H7Ovcfzb4qWHJbhUlQYWjbBFn4hi3zxkvE77I5Ds=,tag:aMBp7g4lKPJuRR73t+i/VA==,type:str]
  MAIN_DOMAIN: ENC[AES256_GCM,data:Jw9ii3nq5kAe77Pa,iv:x1QD7Qk5VVL+6uLm2DA42cAMrrIBtTr2R7jG/e7utSo=,tag:MYf74cqWRgp8E69oJtvvVQ==,type:str]
sops:
  age:
    - recipient: age14c693pdqe6ucz358tteussmwt96fyqz2zs8d656td2av3y0s7ugqklja8z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveCt1a0R6M0dPVlZLZmhu
        aHNnQmd4SHlPT1RmTDl3anpIbEVHbjZDc1RFCkxxeW1henpjQS9yY2pLY0dEME12
        cTVjSTVpaEJmUEVTenlrZWI5MlFPZHcKLS0tIHZUM1lRUDdIUThiZ3prdmFtNDZ1
        RUZMY0R6RXViY1FYeUE0RnFkTit0ajgKshP4R2Qf3NVIxWzwOP8aEXdZSP8yOkkN
        3swDHrcyrfCWbEBUVoWE1VMqoldpQ//YmJD/KQ/UJ2pZoJJ0riRwWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-08T14:53:36Z"
  mac: ENC[AES256_GCM,data:iyuPynZBPkMkONjwZxfE7qiGCx39heMV88xZs3FRRM2dErXB9TYFaFR6zDphDsi5Frxpqk+aT4A9JewwGJM94Y9txSjv46VfYC+IX6gFJw91tAx34bu/4oa9YoDj5ZxdV2QHL3S6zv6DxAErobOI02+OCKnW63crYVYt21nM7+Q=,iv:5mUhq24iAxNEThpAe9BkuakR64JVSe9Rea8Kff80fXQ=,tag:CgicmvY2FZ4IXDExLWfnJA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
