---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
  interval: 1h
  values:
    leaderElect: true
    image:
      repository: ghcr.io/external-secrets/external-secrets
    serviceMonitor:
      enabled: true
    grafanaDashboard:
      enabled: true
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      replicaCount: 2
      serviceMonitor:
        enabled: true
